apiVersion: rbac.authorization.k8s.io/v1
kind: CLusterRoleBinding
metadata:
  name: cluster-role-admin-binding
subjects:
- kind: User
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  kind: ClusterRole
  name: cluster-administrator
  apiGroup: rbac.authorization.k8s.io/v1
