# dockerfile
# FROM ubuntu
# ENTRYPOINT ["sleep"]
# CMD ["5"]

# to override through k8s,

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: [ "sleep2.0" ]
    args: [ "10" ]
