apiVersion: v1
kind: Config
current-context: dev-user@google
clusters:
- name: my-kube-playground
  cluster:
    certficate-authority: ca.cert
    server: https://my-kube-playground:6443
- name: development # values hidden
- name: production
- name: google

contexts:
- name: my-kube-admin@my-kube-playground
  context:
    cluster: my-kube-playground
    user: my-kube-admin
    namespace: finance
- name: dev-user@google
- name: prod-user@production

users:
- name: my-kube-admin
  user:
    client-certificate: admin-crt
    client-key: admin.key
- name: admin
- name: dev-user
- name: prod-user

# k config view 
# k config use-context prod-user@production
