apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: myapp
    image: webapp
    ports:
      containerPort: 8080
    livenessProbe:
      httpGet: /api/ready # or tcpSocket: or exec: command: - cat - /app/is-ready 
      port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5 # how often we want the probe
      failureThreshold: 8
