apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mypvclaim
spec: 
  accessModes:  
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests: 
      storage: 8Gi
  sotrageClassName: slow
  selector: 
    matchLabels:
      release: "stable"
    matchExpressions: 
      - {key: environment, operator: In, values: [dev]}