# creating a resource quota for my-namespace
apiVersion: v1
kind: ResourceQuota
metadata: 
  name: quota-for-default-namespace
  namespace: my-namespace
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "10"
    limits.memory: "16Gi"
    services: "10"

