apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
    type: front-end
  ports:
  - port: 80 # refers to port of service
    targetPort: 80 # refers to port of pod
    nodePort: 30002 # port of the node. Same port applies to all the nodes 
