apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: alpine
    image: alpine
    command: [ "/bin/sh", "-c" ]
    args: [ "shuf -i 0-100 -n 1 >> /opt/numberout;" ]
    volumeMounts:
    - mountPath: /opt # path within the container
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /data # path on the host
      type: Directory
---
# suppose we want to store on AWS instead of local node
volumes:
- name: data-volume
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4
